export const AUTH_TEXT = {
  login: {
    title: "Welcome Back",
    description: "Enter your credentials to access your account",
    usernameLabel: "Username",
    usernamePlaceholder: "Enter your username",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    submitButton: "Login",
    registerButton: "Register",
    noAccount: "Don't have an account?",
    registerLink: "Create one now",
  },
  register: {
    title: "Create an Account",
    description: "Join us today and start shopping!",
    usernameLabel: "Username",
    usernamePlaceholder: "Choose a unique username",
    nameLabel: "Full Name",
    namePlaceholder: "Enter your full name",
    emailLabel: "Email",
    emailPlaceholder: "Enter your email address",
    passwordLabel: "Password",
    passwordPlaceholder: "Create a strong password",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your password",
    submitButton: "Sign Up",
    alreadyHaveAccount: "Already have an account?",
    loginLink: "Login here",
  },
};
